# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 晨曦的小屋
subtitle: ''
description: ''
keywords:
author: 晨曦
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
all_minifier: true
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: redefine
deploy:
  type: git
  repo: https://github.com/xcx2006/xcx2006.github.io
  branch: main

search:
  path: search.json
  field: post
  content: true
  format: striptags
menu: #you can customize, i18n files are in the theme's languages folder. fa-regular recommended
  Home:
    path: /
    icon:  # can be empty
  Archives:
    path: /archives
    icon:  # can be empty
  # Status:
  #   path: https://status.evanluo.top/
  #   icon: fa-regular fa-chart-bar
  Categories:
     icon:
     path: /categories
  About:
     icon:
     path: /about
  # Picture: /picture
  #   submenus:
  #     unlock-music: /about
  #     Github: https://github.com/EvanNotFound/hexo-theme-redefine
  #     Blog: https://www.evanluo.top
  #     Friends: /friends
  # Links:
  #   icon: fa-regular fa-link
  #   submenus:
  #     Link1: /links
  #     Link2: /link2
  #     Link3: /link3
uglify:
    mangle: true
    output:
    compress:
    exclude:
        - "*.min.js"
        - "**/*.min.js"

clean_css:
    exclude:
        - "*.min.css"
        - "**/*.min.css"

html_minifier:
    collapseBooleanAttributes: true
    collapseWhitespace: true
    ignoreCustomComments: [!!js/regexp /^\s*more/]
    removeComments: true
    removeEmptyAttributes: true
    removeScriptTypeAttributes: true
    removeStyleLinkTypeAttributes: true
    minifyJS: true
    minifyCSS: true
live2d:
      enable: true
      scriptFrom: local
      model:
        use: live2d-widget-model-koharu #模型选择
      display:
        position: center  #模型位置
        width: 150   #模型宽度
        height: 300  #模型高度
      mobile:
        show: false  #是否在手机端显示
feed:
  type: atom
  path: atom.xml
  limit: 20
